---
title: "0_setup"
params:
  species:  "DOCCOR,DOCCO,DCCO,DCCOR,Double-crested Cormorant,Double Crested Cormorant"
  # dir.orig.data: "C:/Users/aroyle/DOI/Burnett, Jessica L - cormorants/dubcorm-data-backup/"
  dir.orig.data: "C:/Users/jburnett/OneDrive - DOI/research/cormorants/dubcorm-data-backup/"
  dir.proj: "C:/Users/jburnett/documents/github/dubcorms/inst/tutorials/DCCO/"
  countries: "Canada, USA,United States,United States of America" # used to create base maps
  states: "FL, Florida, GA, Georgia" # states/regions of interest
  overwrite.jdat: FALSE
  year.range: 2008:2019 # for now, supply a range as integers (will fix later in `clean_params()`)
  mmyyyy: "Oct-2021" # month and year of most recent ebird EBD/samp download in file.
  grid.size: 1.00 #== 1 dec deg
  min.yday: 91  # approximate breeding season day start (day of year)
  max.yday: 245 # approximate breeding season day end   (day of year)
  ebird.protocol: c("Traveling", "Stationary")
  complete.checklists.only: TRUE # ebird
  max.effort.mins: 180 ## arbitrary choice; integer
  max.effort.km:  5 #This is coarse also, typically 5km or less
  max.num.observers: 10 # ebird
  crs.target: 4326 # 4326 == unprojected; 5070=Alberts equal area (used by USGS)
  # include.unid: FALSE ## Whether or not to include UNIDENTIFIED // hybrid species
  get.sunlight: FALSE # if you need to calculate sun/moonrise times set to TRUE (comp. expenesive for eBird data so don't do this unless you realllly want it.) 
---

```{r chunks, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>", 
  # message = TRUE, 
  # echo=FALSE, 
  # warning=FALSE, 
  tidy=TRUE, 
  include=FALSE
)
```

```{r libraries, echo=TRUE}
## Users may run into issues when installing the following packages:
devtools::install_github("ropensci/rnaturalearth", force=FALSE) ## must install from GH -- source has unresolved issues for 2+years (see issue https://github.com/ropensci/rnaturalearthhires/issues/1)
unloadNamespace("dubcorms") # just a precaution to ensure we get most recent dev version of pkg
devtools::install_github("trashbirdecology/dubcorms", force=FALSE)

### specify packages that we call often 
pkgs <- c("dubcorms","bbsAssistant","ggplot2","reshape2",
          "stringr","dplyr","sf", "jagsUI")
invisible(lapply(pkgs, library, character.only = TRUE))
rm(pkgs)
```

# Evaluate Parameters from YAML
Next, use function `dubcorms::eval_params` to clean up the parameters, then assign all  to global environment.  
```{r eval-params, eval=TRUE, include=FALSE}
# eval parameters
params.temp <- eval_params(params) # we cannot save as params--won't allow us to overwrite
list2env(params.temp, envir = environment())
rm(params.temp) # remve temp 
```


# Specify Directories
```{r specs-dirs}
# proj.shorthand: this will make all directories within a new dir in dir.proj. this is useful for iterating over species/time/space and saving all resulting information in those directories.
subdir.proj <- proj.shorthand(species, states, grid.size, year.range)
dirs <- dir_spec(dir.orig.data, dir.proj, subdir.proj) # create series of directories for later use.
list2env(dirs)# bind the dir values as named global objects
```

# Specify and Remove Junk
```{r specify-junk}
# save a list of elements we always want to keep in memory
# we also distinguish between the base argumensts for use later in making metadata tables describing our jags objects. 
args.save <- args.save.base <- c("args.save.base", ls())
```

# Spatial Grid
```{r make-grid}
grid <- make_spatial_grid(dir.spatial.out, interactive.map = TRUE)
```

