# SPECIES LIST ------------------------------------------------------------
#' Species Lookup Table for BBS and eBird Data
#'
#' \describe{
#'   \item{}{}
#' }
#'

# b.spp <- bbsAssistant::species_list
# e.spp <- auk::ebird_species(x=unique(species_lookup$English_Common_Name))
# auk:::auk_species()

# JDAT CONTENTS -----------------------------------------------------------
#' Descriptions of JDAT Contents
#' @format A data frame
#' \describe{
#'   \item{name}{object name}
#'   \item{description}{informal description of item}
#'   \item{note}{supplementary information}
#'   \item{class}{expected class of object}
#'   \item{dims}{expected dimensions of object, relative to parent list. Not provided for objects of class list or single}
#' }
jdat.contents <-
  structure(
    list(
      name = c(
        "Xp",
        "C",
        "nSites",
        "nYears",
        "nGrids",
        "idsGrids",
        "idsSites",
        "idsYears",
        "idsGridsbySiteYear",
        "nGridsBySiteByYear",
        "nMaxGrid",
        "Xg",
        "XY",
        "area",
        "pregam",
        "jags.data",
        "jags.ini",
        "jags.fn"
      ),
      description = c(
        "site-level detection covariates",
        "observed counts (unadjusted)",
        "number of sites (i.e. routes, checklists) with data ",
        "number of years with data",
        "number of grids within which each site falls",
        "identities of grid cells with data (within which the sites in C fall)",
        "identities of sites with data (in C)",
        "identities of years with data (in C)",
        "identities of the grid cells within which a route falls each year ",
        "number of grid cells per year by route with data",
        "maximum number of grids within which a site (i.e. BBS route) falls",
        "grid-level covariates",
        "X,Y (lon,lat) coordinates of grid cell centroid",
        "area (m^2) of the grid cell ",
        "",
        "data for use in gam portion of JAGS model; comprises y, n, X",
        "initial values for b, rho",
        "full path to the output JAGS gam model specfication"
      ),
      note = c(
        "each df represents a single detection covariate",
        "",
        "number of sites represented in respective observations data",
        "number of years represented in respective observations data",
        "number of grid cells represented in respectve observations data",
        "",
        "",
        "",
        "only available for BBS ",
        "only available for BBS ",
        "used as a nested index in JAGS; only available for BBS ",
        "used as linear predictors for lambda.grid",
        "",
        "",
        "only present in gam list; generated by mgcv::jagam()",
        "only present in gam list; generated by mgcv::jagam()",
        "only present in gam list; generated by mgcv::jagam()",
        "only present in gam list"
      ),
      class = c(
        "list of matrices",
        "matrix",
        "integer",
        "integer",
        "integer",
        "vector",
        "vector",
        "vector",
        "array",
        "matrix",
        "integer",
        "",
        "matrix",
        "vector",
        "list",
        "list",
        "list",
        "character string"
      ),
      dims = c(
        "nSites x nYears",
        "nSites x nYears",
        "",
        "",
        "",
        "length=nGrids",
        "length=nSites",
        "length=nYears",
        "nSites x nYears x nMaxGrid",
        "nSites x nYears",
        "",
        "",
        "",
        "length=nGrids",
        "",
        "",
        "",
        ""
      )
    ),
    class = "data.frame",
    row.names = c(NA,-18L)
  )


usethis::use_data(jdat.contents, internal = FALSE, overwrite=TRUE)

#' # REGION CODES ------------------------------------------------------------
#' #' Lookup Table for ISO Codes
#' #'
#' #'
#' #' @importFrom stringr str_detect
#' #' @importFrom dplyr select filter
#' #' @format A data frame
#' library(dplyr)
#'
#' # grab ebird region codes
#' ebird.codes <- auk::ebird_states %>%
#'   rename()
#'
#' # grab bbs region codes
#' bbs.codes <- bbsAssistant::region_codes %>%
#'   dplyr::filter(!stringr::str_detect())
#' setdiff(tolower(bbs.codes$State),toupper(iso.codes$name))
#'
#' iso.codes <- rnaturalearth::ne_states() %>%
#'   as.data.frame() %>%
#'   # tibble::column_to_rownames(name_en) %>%
#'   dplyr::select(name_en, iso_3166_2, iso_a2, , name_fr, name_es)
#' str(iso.codes$iso_3166_2)
#' str(iso.codes$iso_a2)
#' str(auk::ebird_states$country_code)
#' # Add a column for eBird file identification




# Add a column for BBS data subsetting
# region.codes <- iso.codes

# usethis::use_data(region.codes, internal = FALSE, overwrite=TRUE)
# END DATA ----------------------------------------------------------------



